// THIS IS A SMALL EXAMPLE, WHICH YOU MOST LIKELY WOULD HAVE DONE IN CLASS.
// THIS EXAMPLE IS USED TO DEMONSTRATE THE VERY BASICS OF PROGRAMMING,
// AS WELL AS TO GET YOU TYPING AND RUNNING YOUR FIRST BIT OF CODE.
// THIS IS JUST AN EXAMPLE, SO THERE WON'T BE ANY EXPLANATION.
// THAT WILL COME WITH FUTURE VIDEOS!!!
#include <iostream>

using namespace std;

int main() {
        cout << "Hello, World!" << endl;

        return 0;
}

// THERE, YOU HAVE WRITTEN YOUR FIRST PROGRAM.
// ALL IT DOES IS DEMONSTRATE PRINTING TO THE STANDARD OUTPUT, WHICH IN THIS
// CASE IS THE TERMINAL WINDOW. IN WINDOWS, IT WOULD BE THE CONSOLE, COMMAND
// LINE
