require("awful.autofocus")
require('bits&pieces').error_handling()
require('bits&pieces').set()
require('layouts').layouts()
require("tags").setup()
require('widgets').setup()
require("rules").set()
require("signals").signals()

root.keys(require('bindings').global())
