#!/bin/bash

if [ -z "$DISPLAY" ]; then
        echo "cannot run without a display. exiting..."
        sleep .5
        exit
fi

function Code {
        if [ -n "`tmux ls | grep "coding"`" ]; then
                termite --name coding -t "  " -e "tmux attach -t coding"
        else
                termite --name coding -t "  " -e "tmux new -s 'coding'"
        fi
}

( ( cd $HOME/git/featherwings/coding; Code ) & )
